workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Install pods
        script: |
          find . -maxdepth 2 -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and App Store release
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
